/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kjh_shakeit_main_more_ImageFilterActivity */

#ifndef _Included_com_example_kjh_shakeit_main_more_ImageFilterActivity
#define _Included_com_example_kjh_shakeit_main_more_ImageFilterActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kjh_shakeit_main_more_ImageFilterActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_kjh_shakeit_main_more_ImageFilterActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_kjh_shakeit_main_more_ImageFilterActivity
 * Method:    ConvertToBlur
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_kjh_shakeit_main_more_ImageFilterActivity_ConvertToBlur
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_kjh_shakeit_main_more_ImageFilterActivity
 * Method:    ConvertToContrast
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_kjh_shakeit_main_more_ImageFilterActivity_ConvertToContrast
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_example_kjh_shakeit_main_more_ImageFilterActivity
 * Method:    ConvertToBrightness
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_kjh_shakeit_main_more_ImageFilterActivity_ConvertToBrightness
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
